### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by Zzij** [TheFreeOne/electron-webrtc-meeting-room#2]
你好：
     我最近也在做一个基于vue和electron的webrtc客户端，使用vue在网页上通话视频都是正常的，但是放到electron中，发现没有声音也没法开启视频，这个情况你有遇到过吗？ 怎么解决的，谢谢了

**Comment by TheFreeOne** [comment]
windows 设置中检查 有没有给electron相关权限

**Comment by TheFreeOne** [comment]
除了检测隐私权限之外，就是看 控制台 中的报错信息了

**Comment by Zzij** [comment]
麦克风权限有的，说话对端也能听到，但是对端的声音electron客户端不播放没声音，看中控台没有报错，而且也看到控制台打印audiostream，网上查资料也没有发现此类问题，所以想请教下是不是还要在代码中需要开启electron的什么特性，

**Comment by TheFreeOne** [comment]
我用的16.0的版本electron，没有发现需要开启什么electron特性的地方；你使用的是原生的webrtc代码吗还是使用了相关的框架？

**Comment by TheFreeOne** [comment]
创建BrowserWindow的时候webPreferences下有webSecurity和contextIsolation两个值，你可以尝试修改成false之类的

**Comment by Zzij** [comment]
加了没有效果，用的 webrtc-adapter库，只能再试试，对前端不熟，头大。谢谢你的回答

**Comment by TheFreeOne** [comment]
https://github.com/TheFreeOne/electron-webrtc-meeting-room/tree/master/electron-meeting-room-client/html/mesh/meeting 
            这里头是用原生写的，写的比较乱，如果你有空可以将就着参考一下  (你都用vue了，感觉应该对前端比较熟悉才是)

**Comment by Zzij** [comment]
感谢，我在试试，不行的话 试试你的方法 :)。我主写java，前端都是到处拼接的。。。

**Comment by TheFreeOne** [comment]
好家伙，跟我一样也是java，前端我也是各种搜的，你弄webrtc是作业还是工作？

**Comment by Zzij** [comment]
哈哈哈哈哈  都是为了工作，不然这东西 一般人都接触不到

**Comment by TheFreeOne** [comment]
确实，那你加油咯

**Comment by Zzij** [comment]
借你吉言:)

**Comment by AdragonL** [comment]
请问已经解决了吗 我用的是electron19.0
在chrome上是没有问题的 但是在electron播放不了媒体流 已经是获取了对方的MediaStream 播放本地媒体流可以

**Comment by AdragonL** [comment]
在本地跑无法建立webrtc连接

**Comment by TheFreeOne** [comment]
> 在本地跑无法建立webrtc连接

你好，能否提供一个小例子

**Comment by AdragonL** [comment]
我这边可以把包发你 帮忙看看吗
我qq 865054055

**Comment by TheFreeOne** [comment]
> 我这边可以把包发你 帮忙看看吗 我qq 865054055

加你了，或者放到github上也行，有代码更好

**Comment by AdragonL** [comment]
好

**Comment by AdragonL** [comment]
你好 qq没有收到请求喔 或者我加你？

**Comment by TheFreeOne** [comment]
> 你好 qq没有收到请求喔 或者我加你？

代码例子发我邮箱吧 free077@qq.com

**Comment by AdragonL** [comment]
好的

**Comment by AdragonL** [comment]
已发送 麻烦大佬帮忙看看

**Comment by TheFreeOne** [comment]
> 已发送 麻烦大佬帮忙看看

ok

**Comment by TheFreeOne** [comment]
> 已发送 麻烦大佬帮忙看看

初步可能是用了同一个RTCPeerConnection的原因，我有空再看看

**Comment by AdragonL** [comment]
好的 谢谢哈 大佬
